on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run tests
        run: npm test
      - name: Set up Lcov
        run: sudo apt-get -y install lcov
      - name: Generate report from lcov
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: coverage/lcov.info
          minimum-coverage: 70
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # working-directory: apps/my-first-app
          update-comment: true

