on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run tests
        run: npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: coverage/lcov.info

  report:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lcov.info
      - name: Set up Lcov
        run: sudo apt-get -y install lcov
      - name: Generate report from lcov
        uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcov.info
          minimum-coverage: 70
          artifact-name: coverage-html-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true

